### ISSUE TITLE
Metronome play crash after updating to 2.0.3

### ISSUE THREAD

**Issue by manudicri** [biner88/metronome#22]
Hi @biner88 ,
This is the error when playing:

```
metronome/Metronome.swift:209: Fatal error: 'try!' expression unexpectedly raised an error: Foundation._GenericObjCError.nilError
Lost connection to device.
```

This is a sample code:

```
Metronome metronome = Metronome()..init("assets/sounds/Metr_fl_low_fixed.wav", volume: 100);
metronome.setBPM(120);
metronome.play();

```

it looks like `bufferAccentedClick` is nil

```
let bufferAccentedClick = AVAudioPCMBuffer(pcmFormat: audioFileAccented.processingFormat, frameCapacity: beatLength)!
try! audioFileAccented.read(into: bufferAccentedClick)
```

This is my audio:
2.8 KB in size
Duration: 0.03 seconds (!)
Sample rate: 44100 Hz
Mono (1 channel)
Bits per sample: 16

Please help

**Comment by manudicri** [comment]
Temporary fixed it by adding the `accentedPath` and not leaving it null

**Comment by biner88** [comment]
Please refer to the sample code. @manudicri
